Website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^rest/', include('rest.urls', namespace='rest')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^', include('frontend.urls', namespace='frontend'))
]
#urlpatterns += staticfiles_urlpatterns()

api/urls.py
from django.conf.urls import url
from . import views

app_name = 'api' # This is a namespace to seperate different names to use as {% url "namespace:name" addition %}

urlpatterns = [
    url(r'^$', views.list_view, name = 'list_view'),
	url(r'^(?P<symbol>[A-Z]{,5})$', views.detail_view, name = 'detail_view'),
    ]

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.list_view, name = 'list_view'),
	url(r'^(?P<id>[0-9]+)$', views.detail_view, name = 'detail_view')
    ]

frontend/urls.py
from django.conf.urls import url
from . import views

app_name = 'frontend'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^terms', views.terms, name = 'terms'),
    url(r'^contact', views.contact, name = 'contact'),
    ]

blog/models.py
from django.db import models

class Entry(models.Model):
    """ Contains all information about a blogentry """
    date = models.DateField()
    title = models.CharField(max_length=150)
    text = models.TextField()

    class Meta:
        ordering = ['date']
        
    def __unicode__(self):
        return self.title
    def __str__(self):
        return self.title
    def __repr__(self):
        return self.title

frontend/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Entry

# All blogentries
def list_view(request):
    all_entries = Entry.objects.all().order_by('date')[0:100]
    return render(request, 'frontend/blog.html', {"all_entries" :  all_entries})

def detail_view(request, id):
    entry = get_object_or_404(Entry, id=id)
    return render(request, 'frontend/blogpost.html', {"entry" :  entry})

frontend/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'frontend/index.html')

def terms(request):
    return render(request, 'frontend/terms.html')

def contact(request):
    return render(request, 'frontend/contact.html')

frontend/templates/frontend/blog.html
{% extends "frontend/main.html" %}


{% block content %}
    <!-- Header -->
    <section id="header">
        <div class="inner">
            <span class="icon major fa-code"></span>
            <h1>Blog</h1>
            <p>The place where you´ll learn how to retrieve and use our data!</p>
            <ul class="actions">
                <li><a href="/" class="button">Back</a></li>
            </ul>
        </div>
    </section>

    <!-- List -->
    <section id="list", class="main style2">
        <div class="container">
            <ul>
                {% for entry in all_entries %}
                <li>
                    <a href='{% url "blog:detail_view" entry.id %}'>{{ entry.date }}: {{ entry.title }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
</section>

{% endblock %}

frontend/templates/frontend/blogpost.html
{{ entry.text|safe|linebreaks }}

frontend/templates/frontend/chart.html
{% extends "frontend/main.html" %}

{% block content %}
    <!-- Header -->
    <section id="header">
        <div class="inner">
            <span class="icon major fa-line-chart"></span>
            <h1>{{ stock.full_name }}</h1>
                {% if stock.description|length %}
                    <div class="container">
                        <p>{{ stock.description }}</p>
                    </div>
                    <a href="https://de.wikipedia.org/wiki/{{ stock.full_name }}">More on Wikipedia</a>
                {% else %}
                    <p>No Description available.</p>
                {% endif %}
            <ul class="actions">
                <li><a href="/" class="button">Back</a></li>
                <li><a href="/" class="button">Back</a></li>
            </ul>
        </div>
    </section>

    <!-- Price Chart -->
    <section id="price_chart">
        <div class="container">
            {% if data.data %}
                <h2>Price Data for {{ stock.full_name }}:</h2>
                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
                <script type="text/javascript">
                    google.charts.load('current', {'packages':['line']});
                    google.charts.setOnLoadCallback(drawChart);

                    function drawChart() {

                        var data = new google.visualization.DataTable();

                        data.addColumn('string', 'Date');
                        data.addColumn('number', 'price_high');


                        data.addRows([
                            {% for data in price_data %}
                                ["{{ data.date }}", {{ data.price_high }}],
                            {% endfor %}
                            ]);

                        var options = {
                            chart: {
                                title: 'in dollars (USD)',
                                subtitle: ''
                            },
                            height: 500,
                            axes: {
                                x: {
                                    0: {side: 'top'}
                                }
                            }
                        };

                        var chart = new google.charts.Line(document.getElementById('line_top_x'));

                        chart.draw(data, options);
                    }
                </script>

                <div id="line_top_x"></div>
            {% else %}
                <h2>No price data for {{ stock.full_name }} available.</h2>
            {% endif %}
        </div>
    </section> 

    <!-- Table -->
    <section id="two" class="main style2">
        <div class="container">
            {% if fundamental_data %}
            <h2>Fundamental Data for {{ stock.full_name }}:</h2>
            <div class="row 100%">
                {% for info in fundamental_data %}

                    <h3> Publication of the Annual Report: {{ info.date }} </h3>
                    <table>
                        <tr>
                            <th scope="col">end_date</th>
                            <!--<th scope="col">period_focus</th>-->
                            <th scope="col">revenues</th>
                            <th scope="col">op_income</th>
                            <th scope="col">net_income</th>
                            <th scope="col">eps_basic</th>
                            <!--<th scope="col">eps_diluted</th>-->
                            <th scope="col">dividend</th>
                            <th scope="col">cur_assets</th>
                            <th scope="col">cur_liab</th>
                            <!--<th scope="col">cash</th>-->
                            <th scope="col">equity</th>
                            <th scope="col">cash_flow_op</th>
                            <!--<th scope="col">cash_flow_inv</th>
                            <th scope="col">cash_flow_fin</th>-->
                        </tr>
                        <tr>
                            <td>{{ info.end_date }}</td>
                            <!--<td>{{ info.period_focus }}</td>-->
                            <td>{{ info.revenues }}</td>
                            <td>{{ info.op_income }}</td>
                            <td>{{ info.net_income }}</td>
                            <td>{{ info.eps_basic }}</td>
                            <!--<td>{{ info.eps_diluted }}</td>-->
                            <td>{{ info.dividend }}</td>
                            <td>{{ info.cur_assets }}</td>
                            <td>{{ info.cur_liab }}</td>
                            <!--<td>{{ info.cash }}</td>-->
                            <td>{{ info.equity }}</td>
                            <td>{{ info.cash_flow_op }}</td>
                            <!--<td>{{ info.cash_flow_inv }}</td>
                            <td>{{ info.cash_flow_fin }}</td>-->
                        </tr>
                    </table>
                {% endfor %}
            </div>
            {% else %}
                <h2>No fundamental data for {{ stock.full_name }} available.</h2>
            {% endif %}

        </div>
    </section>

{% endblock %}

frontend/templates/frontend/contact.html
{% extends "frontend/main.html" %}

{% block content %}
<!-- Header -->
<section id="header">
    <div class="inner">
        <span class="icon major fa-line-chart"></span>
        <h1>Data Driven Investing</h1>
        <p>If you want to contact me, just write me a mail! Or call, or text me on facebook.</p>
        <ul class="actions">
            <li><a href="/" class="button">Back</a></li>
        </ul>
    </div>
</section>

<!-- Contact - Form -->
<section id="contact_data", class="main style1">
    <form name="contact" method="post" action="https://formspree.io/tilllangbein@gmail.com">
        <div class="container">
            <div class="contactus">
                <label>
                    <span>Subject</span>
                    <input type="text" name="Subject" placeholder="Hey!">
                </label>
                <label>
                    <span>Your E-Mail</span>
                    <input type="email" name="Your E-Mail" placeholder="Max@Mustermann.com">
                </label>
                <label>
                    <span>Your Message</span>
                    <input type="text" name="Write me a mail" placeholder="Whats up?">
                </label>
                <button type="submit">Send</button>
            </div>
        </div>
    </form>
</section>

{% endblock %}

frontend/templates/frontend/entry.html
{% extends "frontend/main.html" %}


{% block content %}
    <!-- Header -->
    <section id="header">
        <div class="inner">
            <span class="icon major fa-line-chart"></span>
            <h1>Data Driven Investing</h1>
            <p>This is a list of all stocks I could get for you! Click on any of them to get more details. You can also mark them as favourites!</p>
            <ul class="actions">
                <li><a href="/" class="button">Back</a></li>
            </ul>
        </div>
    </section>

    <!-- FavList 
    <section id="list" , class="main style1">
        <div class="container">
            <h2> Your Favorite Stocks: </h2>
            {% if error_message %}
                <h3>{{ error_message }}</h3>
            {% endif %}
            <ul>
                {% for stock in favs %}
                <li>
                    <a href="{% url "api:detail_view" stock.symbol %}">{{ stock.full_name }}: {{ stock.symbol }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
</section>-->

    <!-- List -->
    <section id="list", class="main style2">
        <div class="container">
            <h2> All Stocks: </h2>
            <ul>
                {% for stock in head %}
                <li>
                    <a href="{% url "api:detail_view" stock.symbol %}">{{ stock.full_name }}: {{ stock.symbol }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </section>

{% endblock %}

frontend/templates/frontend/main.html
<!DOCTYPE HTML>
<html lang="en">
{% load static %}
	<head>	
		<title>Data Driven Investing</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static "/css/main.css" %}" />
	</head>
	<body>

        {% block content %}
		{% endblock %}

		<!-- Footer -->
			<section id="footer">
				<ul class="icons">
					<li><a href="#" class="icon alt fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="https://www.facebook.com/till.langbein" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="https://github.com/kallinikator/equipy" class="icon alt fa-github"><span class="label">GitHub</span></a></li>
					<li><a href="{% url 'frontend:contact' %}" class="icon alt fa-envelope"><span class="label">Contact</span></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; Data Drive Investing</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
				</ul>
			</section>

		<!-- Scripts -->
			<script src="{% static "/js/jquery.min.js" %}"></script>
			<script src="{% static "/js/jquery.scrolly.min.js" %}"></script>
			<script src="{% static "/js/skel.min.js" %}"></script>
			<script src="{% static "/js/util.js" %}"></script>
			<script src="{% static "/js/main.js" %}"></script>

	</body>
</html>